Добавлен модуль core
IPLATFORM-TECH/iplatform-1 pull request #6
Opened 2022-09-10 10:31 UTC by AraItto

2022-09-12 12:33 UTC, a-s-eliseev requested changes

2022-09-12 12:33 UTC, a-s-eliseev commented on core/.gitignore
> +HELP.md
Этот файл лишний. На проект один .gitignore, который в корне

2022-09-12 12:33 UTC, a-s-eliseev commented on core/mvnw
> +#!/bin/sh
Этот файл лишний

2022-09-12 12:33 UTC, a-s-eliseev commented on core/mvnw.cmd
> +@REM ----------------------------------------------------------------------------
Этот файл лишний

2022-09-12 12:33 UTC, a-s-eliseev commented on core/pom.xml
> +    <groupId>space.eliseev.iplatform</groupId>
где-то должно быть указание, что это jar

2022-09-12 12:33 UTC, a-s-eliseev commented on core/src/test/java/space/eliseev/iplatform/core/CoreApplicationTests.java
> +package space.eliseev.iplatform.core;
Пока можно удалить этот класс

2022-09-12 14:23 UTC, AraItto commented
Доработал

2022-09-12 14:31 UTC, a-s-eliseev requested changes

2022-09-12 14:31 UTC, a-s-eliseev commented on core/.mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
это тоже убрать

2022-09-12 14:32 UTC, a-s-eliseev commented
Нужно убрать все файлы maven

2022-09-12 16:21 UTC, AraItto commented
Убрал

2022-09-13 13:54 UTC, a-s-eliseev approved these changes

2022-09-13 13:54 UTC, merged